services:
  react_frontend:
    container_name: react_frontend
    build: ./
    volumes:
      - .:/app
    ports:
      # - "5001:3000"
      # - "10000:10000"
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_BACKEND_SERVICE_URL=${REACT_APP_BACKEND_SERVICE_URL} # Flask service URL (Docker network resolution)
      - PORT=${PORT}